# fly.toml app configuration file generated for vetplus-api-dev on 2023-09-13T18:41:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vetplus-api-qa"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
